#cloud-config
disable_root: true
repo_update: true
repo_upgrade: true
apt:
  preserve_sources_list: true
  sources:
      mongodb-org-4.4:
          source: 'deb https://repo.mongodb.org/apt/ubuntu $RELEASE/mongodb-org/4.4 multiverse'
          key: |
              -----BEGIN PGP PUBLIC KEY BLOCK-----
              Version: GnuPG v1

              mQINBFzteqwBEADSirbLWsjgkQmdWr06jXPN8049MCqXQIZ2ovy9uJPyLkHgOCta
              8dmX+8Fkk5yNOLScjB1HUGJxAWJG+AhldW1xQGeo6loDfTW1mlfetq/zpW7CKbUp
              qve9eYYulneAy/81M/UoUZSzHqj6XY39wzJCH20H+Qx3WwcqXgSU7fSFXyJ4EBYs
              kWybbrAra5v29LUTBd7OvvS+Swovdh4T31YijUOUUL/gJkBI9UneVyV7/8DdUoVJ
              a8ym2pZ6ALy+GZrWBHcCKD/rQjEkXJnDglu+FSUI50SzaC9YX31TTzEMJijiPi6I
              MIZJMXLH7GpCIDcvyrLWIRYVJAQRoYJB4rmp42HTyed4eg4RnSiFrxVV5xQaDnSl
              /8zSOdVMBVewp8ipv34VeRXgNTgRkhA2JmL+KlALMkPo7MbRkJF01DiOOsIdz3Iu
              43oYg3QYmqxZI6kZNtXpUMnJeuRmMQJJN8yc9ZdOA9Ll2TTcIql8XEsjGcM7IWM9
              CP6zGwCcbrv72Ka+h/bGaLpwLbpkr5I8PjjSECn9fBcgnVX6HfKH7u3y11+Va1nh
              a8ZEE1TuOqRxnVDQ+K4iwaZFgFYsBMKo2ghoU2ZbZxu14vs6Eksn6UFsm8DpPwfy
              jtLtdje8jrbYAqAy5zIMLoW+I6Rb5sU3Olh9nI7NW4T5qQeemBcuRAwB4QARAQAB
              tDdNb25nb0RCIDQuNCBSZWxlYXNlIFNpZ25pbmcgS2V5IDxwYWNrYWdpbmdAbW9u
              Z29kYi5jb20+iQI+BBMBAgAoBQJc7XqsAhsDBQkJZgGABgsJCAcDAgYVCAIJCgsE
              FgIDAQIeAQIXgAAKCRBlZAjjkM+x9SKmD/9BzdjFAgBPPkUnD5pJQgsBQKUEkDsu
              cht6Q0Y4M635K7okpqJvXtZV5Mo+ajWZjUeHn4wPdVgzF2ItwVLRjjak3tIZfe3+
              ME5Y27Aej3LeqQC3Q5g6SnpeZwVEhWzU35CnyhQecP4AhDG3FO0gKUn3GkEgmsd6
              rnXAQLEw3VUYO8boxqBF3zjmFLIIaODYNmO1bLddJgvZlefUC62lWBBUs6Z7PBnl
              q7qBQFhz9qV9zXZwCT2/vgGLg5JcwVdcJXwAsQSr1WCVd7Y79+JcA7BZiSg9FAQd
              4t2dCkkctoUKgXsAH5fPwErGNj5L6iUnhFODPvdDJ7l35UcIZ2h74lqfEh+jh8eo
              UgxkcI2y2FY/lPapcPPKe0FHzCxG2U/NRdM+sqrIfp9+s88Bj+Eub7OhW4dF3AlL
              bh/BGHL9R8xAJRDLv8v7nsKkZWUnJaskeDFCKX3rjcTyTRWTG7EuMCmCn0Ou1hKc
              R3ECvIq0pVfVh+qk0hu+A5Dvj6k3QDcTfse+KfSAJkYvRKiuRuq5KgYcX3YSzL6K
              aZitMyu18XsQxKavpIGzaDhWyrVAig3XXF//zxowYVwuOikr5czgqizu87cqjpyn
              S0vVG4Q3+LswH4xVTn3UWadY/9FkM167ecouu4g3op29VDi7hCKsMeFvFP6OOIls
              G4vQ/QbzucK77Q==
              =eD3N
              -----END PGP PUBLIC KEY BLOCK-----

users:
    - default
    - name: appuser
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      ssh-authorized-keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC04MSVVIsoItWZJQLxMF4TeXWA41gnvvtZj/0/IrIuz+ZtlpjVi4WVmZuSU41yYMWzyc8BPJSvCLvxe6DutO6FyUOrV6x4zhXswk4vF05NhjUuE3Mj4tKor6ZFfylDlnnzvtY5U86rejKBUUf/ZFbfgyen1B+MEbZO2VOUAa2kY8XM7GeMiuQOKQRu5l1YYSdK8xFuxXGj4ICv1i0IS5YIr1hosvRNWBAyKH90KPsKDtVEDNweL8sTZLSr7rRGN9mN1TV4grhgE5xAyY2NEhXNEP52LIXyFdMJbU1St1aLkyxePqcYMZIH1ECrVOAsPeLSFT3/AeZ+8TtO2X866itR47hOykTXeM1FmWcBzDqTYDpradeTCUYWVNmn+1vjwrqG+VCUiSVOoPCjLhgOuWdr55uuHolqvlK1pTYCEAfcMtljqLg0sFWYwqNGjOzDvqdE0oZVSrvMnFcjXDfFIsdBycF/v/MIRCI6N02vx7R5PwwUK7hyHJjcMrFKXVMGsbE="

packages:
  - apt-transport-https
  - ca-certificates
  - git
  - ruby-full
  - ruby-bundler
  - build-essential
  - mongodb-org

runcmd:
  - [ systemctl, enable, mongod ]
  - [ systemctl, start, mongod ]
  - [ git, clone, -b, monolith, "https://github.com/express42/reddit.git" ]
  - [ cd, reddit ]
  - [ bundle, install ]
  - [ puma, -d ]
